---
title: "ProcessingJsonPredictions"
author: "Ben Weinstein"
date: "January 16, 2017"
output: html_document
---

```{r,warning=F,message=F}
library(ggplot2)
library(dplyr)
library(reshape2)
library(stringr)
library(jsonlite)
library(yaml)
library(knitr)

#set sys args
args = commandArgs(trailingOnly=TRUE)
Month<-args[1]
```

#Access CloudBucket

```{r}
Sys.setenv("GCS_AUTH_FILE" = "C:/Users/Ben/Dropbox/Google/MeerkatReader-9fbf10d1e30c.json")
library(googleCloudStorageR)
#it should authenticate but its not doing it.
gcs_auth()
gcs_global_bucket("api-project-773889352370-ml")
#list objects
objects <- gcs_list_objects()

#find the objects we want
todl<-which(str_detect(objects$name,"prediction.results"))

for(x in todl){
gcs_get_object(objects$name[x], saveToDisk = objects$name[x])
}
#get file list.
filnames<-list.files("Prediction/yamls",full.names = T)
```

```{r}
ndjson<-lapply(filnames,function(x){stream_in(file(x))})
#strip out scores.
ndj<-lapply(ndjson,function(x){
  x %>% select(key,prediction_label=prediction)
})
mdat<-bind_rows(ndj)

#extract key
mdat$key<-str_match(mdat$key,"/(\\d+_\\d+).jpg")[,2]
```

```{r}
#Training Data
tdata<-read.csv("C:/Users/Ben/Dropbox/MeerkatReader/Output/TrainingData.csv",header=F)
colnames(tdata)<-c("original","key","True_Class_original")

dict<-read.csv("cloudML/dict.txt",header=F)
colnames(dict)<-"Class"
dict$label<-seq(0,nrow(dict)-1,1)

#for now replace to strings, make new classes
tdata$TrueClass<-tdata$True_Class_original
levels(tdata$TrueClass)[levels(tdata$TrueClass)=="/"]<-"Forward_slash"
levels(tdata$TrueClass)[levels(tdata$TrueClass) %in% c(0,1,2,3,4,5,6,7,8,9)]<-c("Zero","One","Two","Three","Four","Five","Six","Seven","Eight","Nine")

#merge labels and classes
tdata<-merge(tdata,dict,by.x="TrueClass",by.y="Class")

#trim out the full path
tdata$key<-str_match(tdata$key,"/MeerkatReader/\\w+/(\\w+).jpg")[,2]
```

```{r}
#temp file location
f<-"C:/Users/Ben/Desktop/test.json"
#load predictions
dat<-yaml.load_file(f)

dict<-read.csv("C:/Users/Ben/Documents/MeerkatReader/BuildModel/cloudML/dict.txt",header=F)
colnames(dict)<-"Class"
dict$label<-seq(0,nrow(dict)-1,1)
```

# Create prediction frame
```{r}
organize<-function(x){
  data.frame(key=x$key,label=seq(0,length(x$scores)-1,1),scores=x$scores)
}

mdat<-bind_rows(lapply(dat[[1]],organize))

#get the consensus top pick for each
prediction<-mdat %>% group_by(key) %>% filter(scores %in% max(scores)) %>% select(key,label)

#get class from label
prediction<-merge(prediction,dict) %>% select(key,prediction=Class)
```
'
# Recombine into words
Needs to be done seperately for camera, date and time
```{r}
keyframe<-data.frame(prediction,str_match(prediction$key,"/(\\w+)_(\\w+).jpg")[,-1])
colnames(keyframe)<-c("key","prediction","image","letter_index")

#combine letters by index
towrite<-keyframe %>% group_by(image) %>% summarize(key=unique(key),camera_id=paste(letter_index,collapse="")) %>% select(-image)

#append?
write.csv(towrite,"prediction.csv")
```
