---
title: "Model performance"
author: "Ben Weinstein"
date: "January 13, 2017"
output: html_document
---

```{r,warning=F,message=F}
library(ggplot2)
library(dplyr)
library(reshape2)
library(stringr)
library(jsonlite)
library(yaml)
library(knitr)
opts_chunk$set(warning=F,message=F,echo=F)
```

#Access CloudBucket

```{r}
Sys.setenv("GCS_AUTH_FILE" = "C:/Users/Ben/Dropbox/Google/MeerkatReader-9fbf10d1e30c.json")
library(googleCloudStorageR)
#it should authenticate but its not doing it.
gcs_auth()
gcs_global_bucket("api-project-773889352370-ml")
#list objects
objects <- gcs_list_objects()

#find the objects we want
todl<-which(str_detect(objects$name,"prediction.results"))

for(x in todl){
gcs_get_object(objects$name[x], saveToDisk = objects$name[x])
}
#get file list.
filnames<-list.files("Prediction/",full.names = T)
```

```{r}
ndjson<-lapply(filnames,function(x){stream_in(file(x))})
#strip out scores.
ndj<-lapply(ndjson,function(x){
  x %>% select(key,prediction_label=prediction)
})
mdat<-bind_rows(ndj)

#extract key
mdat$key<-str_match(mdat$key,"/(\\d+_\\d+).jpg")[,2]
```

```{r}
#Training Data
tdata<-read.csv("C:/Users/Ben/Dropbox/MeerkatReader/Output/TrainingData.csv",header=F)
colnames(tdata)<-c("original","key","True_Class_original")

dict<-read.csv("cloudML/dict.txt",header=F)
colnames(dict)<-"Class"
dict$label<-seq(0,nrow(dict)-1,1)

#for now replace to strings, make new classes
tdata$TrueClass<-tdata$True_Class_original
levels(tdata$TrueClass)[levels(tdata$TrueClass)=="/"]<-"Forward_slash"
levels(tdata$TrueClass)[levels(tdata$TrueClass) %in% c(0,1,2,3,4,5,6,7,8,9)]<-c("Zero","One","Two","Three","Four","Five","Six","Seven","Eight","Nine")

#merge labels and classes
tdata<-merge(tdata,dict,by.x="TrueClass",by.y="Class")

#trim out the full path
tdata$key<-str_match(tdata$key,"/MeerkatReader/\\w+/(\\w+).jpg")[,2]
```

#Tesseract Data

```{r cars}
tesdat<-read_json("tesseract.json")
tesdat<-melt(tesdat)
colnames(tesdat)<-c("Tesseract_Prediction","key")
```

#Combine for known sequences
```{r}
#merge cloudml data
kn<-merge(mdat,tdata,by=c("key"))

#merge tesseract data
kall<-merge(kn,tesdat,by="key")

#reorder
kall<-kall %>% select(key,label,prediction_label,Tesseract_Class=Tesseract_Prediction)

#merge to classes
#get true classes
mc1<-merge(kall,dict,by.x="label",by.y="label")
colnames(mc1)[5]<-c("True_Class")

#Prediction classes
mc2<-merge(mc1,dict,by.x="prediction_label",by.y="label")
colnames(mc2)[6]<-c("Cloudml_Class")

#relabel classes
#replot numberic labels
levels(mc2$Cloudml_Class)[levels(mc2$Cloudml_Class) %in% "Forward_slash"]<-"\\/"
levels(mc2$Cloudml_Class)[levels(mc2$Cloudml_Class) %in% "Zero"]<- 0
levels(mc2$Cloudml_Class)[levels(mc2$Cloudml_Class) %in% "One"]<- 1
levels(mc2$Cloudml_Class)[levels(mc2$Cloudml_Class) %in% "Two"]<- 2
levels(mc2$Cloudml_Class)[levels(mc2$Cloudml_Class) %in% "Three"]<- 3
levels(mc2$Cloudml_Class)[levels(mc2$Cloudml_Class) %in% "Four"]<- 4
levels(mc2$Cloudml_Class)[levels(mc2$Cloudml_Class) %in% "Five"]<- 5
levels(mc2$Cloudml_Class)[levels(mc2$Cloudml_Class) %in% "Six"]<- 6
levels(mc2$Cloudml_Class)[levels(mc2$Cloudml_Class) %in% "Seven"]<- 7
levels(mc2$Cloudml_Class)[levels(mc2$Cloudml_Class) %in% "Eight"]<- 8
levels(mc2$Cloudml_Class)[levels(mc2$Cloudml_Class) %in% "Nine"]<- 9

levels(mc2$True_Class)[levels(mc2$True_Class) %in% "Forward_slash"]<-"//"
levels(mc2$True_Class)[levels(mc2$True_Class) %in% "Zero"]<- 0
levels(mc2$True_Class)[levels(mc2$True_Class) %in% "One"]<- 1
levels(mc2$True_Class)[levels(mc2$True_Class) %in% "Two"]<- 2
levels(mc2$True_Class)[levels(mc2$True_Class) %in% "Three"]<- 3
levels(mc2$True_Class)[levels(mc2$True_Class) %in% "Four"]<- 4
levels(mc2$True_Class)[levels(mc2$True_Class) %in% "Five"]<- 5
levels(mc2$True_Class)[levels(mc2$True_Class) %in% "Six"]<- 6
levels(mc2$True_Class)[levels(mc2$True_Class) %in% "Seven"]<- 7
levels(mc2$True_Class)[levels(mc2$True_Class) %in% "Eight"]<- 8
levels(mc2$True_Class)[levels(mc2$True_Class) %in% "Nine"]<- 9

#resort levels
mc2$True_Class<-factor(mc2$True_Class,levels=sort(levels(mc2$True_Class)))
mc2$Cloudml_Class<-factor(mc2$Cloudml_Class,levels=sort(levels(mc2$Cloudml_Class)))
mc2$Tesseract_Class<-factor(mc2$Tesseract_Class,levels=sort(levels(mc2$Tesseract_Class)))

#column order 
mc2<-mc2 %>% select(key,True_Class,Cloudml_Class,Tesseract_Class)

#combine all tesseract letters to upper
mc2$Tesseract_Class<-toupper(mc2$Tesseract_Class)
#refactor
mc2$Tesseract_Class<-factor(mc2$Tesseract_Class)
mc2$Tesseract_Class<-factor(mc2$Tesseract_Class,levels=sort(levels(mc2$Tesseract_Class)))
```

#Accuarcy

## CloudML

```{r}
conf_matrix<-as.matrix(table(mc2$True_Class,mc2$Cloudml_Class,deparse.level = 2))
conf_matrix<-conf_matrix/apply(conf_matrix,1,sum)

mc<-melt(conf_matrix)
colnames(mc)<-c("True","Predict","value")

#remove 0's
cloudml<-mc %>% filter(!value==0)
```

### Confusion matrix

```{r,fig.height=4,fig.width=7}

ggplot(cloudml,aes(x=True,y=Predict,fill=value)) + geom_tile() + theme_bw() + scale_fill_continuous(low="blue",high="red",labels=scales::percent) + labs(x="True",y="Predicted",fill="Accuracy") + ggtitle("CloudML")
ggsave("Figures/ConfusionMatrix_cloudml.jpg",height=4,width=6)
ggsave("Figures/ConfusionMatrix_cloudml.svg",height=4,width=6)

```

## Tesseract

```{r}
conf_matrix_tess<-as.matrix(table(mc2$True_Class,mc2$Tesseract_Class,deparse.level = 2))
conf_matrix_tess<-conf_matrix_tess/apply(conf_matrix_tess,1,sum)

conf_matrix_tess<-melt(conf_matrix_tess)
colnames(conf_matrix_tess)<-c("True","Predict","value")

#remove 0's
conf_matrix_tess<-conf_matrix_tess %>% filter(!value==0)
```

### Confusion matrix

```{r,fig.height=4,fig.width=7}
#order nested to be more complicated 
conf_matrix_tess$Predict<-factor(conf_matrix_tess$Predict,levels=c(levels(conf_matrix_tess$True),levels(conf_matrix_tess$Predict)[!levels(conf_matrix_tess$Predict) %in% levels(conf_matrix_tess$True)]))

ggplot(conf_matrix_tess,aes(x=True,y=Predict,fill=value)) + geom_tile() + theme_bw() + scale_fill_continuous(low="blue",high="red",labels=scales::percent) + labs(x="True",y="Predicted",fill="Accuracy") + ggtitle("Tesseract")
ggsave("Figures/ConfusionMatrix_tesseract.jpg",height=4,width=6)
ggsave("Figures/ConfusionMatrix_tesseract.svg",height=4,width=6)

```

```{r}
tess_acc<-mc2 %>% group_by(True_Class) %>% summarize(Accuracy=sum(toupper(as.character(Tesseract_Class))==toupper(as.character(True_Class)))/n()) %>% mutate(Accuracy=round(Accuracy,2))
paste("Mean Tessaeract accuaracy is ",round(mean(tess_acc$Accuracy),2),sep="")
```