---
title: "TrainingDataAnalysis"
author: "Ben Weinstein"
date: "January 2, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = F,message = F)
```

```{r}
library(dplyr)
library(ggplot2)
```

```{r}
d<-read.csv("C:/Users/Ben/Dropbox/MeerkatReader/Output/TrainingData.csv",header=F)
d$V3<-as.character(d$V3)
```

# Number of classes
```{r}
length(unique(d$V3))
```

# How many images of each class

```{r}
sort(table(d$V3))
```

#replace slashes and numbers, incase of special character

```{r}
d[d$V3=="/","V3"]<-"Forward_slash"
d[d$V3=="0","V3"]<-"Zero"
d[d$V3=="1","V3"]<-"One"
d[d$V3=="2","V3"]<-"Two"
d[d$V3=="3","V3"]<-"Three"
d[d$V3=="4","V3"]<-"Four"
d[d$V3=="5","V3"]<-"Five"
d[d$V3=="6","V3"]<-"Six"
d[d$V3=="7","V3"]<-"Seven"
d[d$V3=="8","V3"]<-"Eight"
d[d$V3=="9","V3"]<-"Nine"
```

```{r}
classes<-as.character(sort(unique(d$V3)))
cat(paste(classes, collapse = "\n"), file = "cloudML/dict.txt") 
```

We are looking for about 200 images per class.

# Split into 80 20 data for each class.
```{r}

#no more than 200 for any given class
#Number the groups
j<-d %>% group_by(V3) %>% do(data.frame(.,case=1:nrow(.))) %>% filter(case<=300)

#add an identifier
j$ID=1:nrow(j)

a<-j %>% group_by(V3) %>% sample_frac(0.85)
test_data<-j[!j$ID %in% a$ID,c("V2","V3")]
train_data<-j[j$ID %in% a$ID,c("V2","V3")]

write.table(test_data,"cloudML/testing_data.csv",row.names=F,col.names = F,sep=",",quote=F)
write.table(train_data,"cloudML/training_data.csv",col.names=F,row.names=F,sep=",",quote=F)
```